project:
  type: website
  output-dir: docs

website:
  site-url: https://utekleong.github.io/
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: pubs.qmd
        text: Research
      - href: blog.qmd
        text: Blog        
      # - href: cv.html
      #   text: Curriculum Vitae
      #   target: _blank
    # right: 
    # - icon: envelope-fill
    #   href: mailto:utek@outlook.com
    # - text: "{{< iconify simple-icons bluesky >}}"
    #   href: https://bsky.app/profile/utekleong.bsky.social
    #   target: _blank
    # - icon: github
    #   href: https://github.com/utekleong
    #   target: _blank
    
  search: false

        
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

